name: Android Build

on:
  push:
    branches:
      - 'main'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Check out Git repository
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci --force
      - name: Create .env file
        uses: ozaytsev86/create-env-file@v1
        with:
          INPUT_ENV_OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          INPUT_ENV_WEB_CLIENT_ID: ${{ secrets.WEB_CLIENT_ID }}
      - name: Build Android Release
        run: npx react-native build-android --mode=release
        env:
          STORE_PASSWORD: ${{ secrets.POEMISA_SIGNING_STORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.POEMISA_SIGNING_KEY_PASSWORD }}
      - name: Upload APK
        id: uploadArtifact
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: ${{ github.workspace }}/android/app/build/outputs/apk/release/app-release.apk
